theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
rainbow-brackets = true
whitespace.render = "all"
end-of-line-diagnostics = "hint"
bufferline = "always"
shell = ["fish", "-c"]

# Auto-completion
idle-timeout = 50
completion-timeout = 5
completion-trigger-len = 0
preview-completion-insert = false
word-completion.trigger-length = 2

# Width
text-width = 120
rulers = [120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"

[editor.statusline]
left = [
  "mode",
  "spacer",
  "spinner",
  "diagnostics",
  "file-type",
  "separator",
  "spacer",
  "version-control",
]
center = ["file-name", "file-modification-indicator", "read-only-indicator"]
right = [
  "selections",
  "position",
  "file-line-ending",
  "file-encoding",
  "file-indent-style",
]
separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
skip-levels = 1

[editor.lsp]
display-progress-messages = true
goto-reference-include-declaration = false

# ============================================ Keybinds ============================================
[keys.insert]
C-p = ["signature_help"]

[keys.select]
"X" = ["extend_line_above"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
ret = ["goto_word"]
C-p = ["signature_help"]
"X" = ["extend_line_above"]

"*" = ["search_selection"] # Select highlighted text for search

# Move lines up and down
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
]

# Swap default file picker keybinds
[keys.normal.space]
f = "file_picker_in_current_directory"
F = "file_picker"

# <space><space> for git commands
[keys.normal.space.space]
r = ":reset-diff-change"
w = ":sh gh_browse %{buffer_name} %{selection_line_start} %{selection_line_end}"
b = ":sh git_blame %{buffer_name} %{cursor_line}"

# + for LSP commands
[keys.normal."+"]
r = ":lsp-restart"
s = ":lsp-stop"
l = ":lsp-workspace-command"
b = ":lsp-workspace-command compile-cascade" # Scala/Metals specific
i = ":lsp-workspace-command build-import"    # Scala/Metals specific

# ยง for config toggling commands
[keys.normal."ยง"]
f = ":toggle-option auto-format"
h = ":toggle-option file-picker.hidden"
g = ":toggle-option file-picker.git-ignore"
i = ":toggle-option lsp.display-inlay-hints"
w = ":toggle-option soft-wrap.enable"

# ' for code/text modification commands
[keys.normal."'"]
f = ":format"
w = ":buffer-close"
W = ":buffer-close-others"
r = ":reload-all"
g = ":reset-diff-change"
")" = "rotate_selection_contents_forward"
"(" = "rotate_selection_contents_backward"
s = ["split_selection_on_newline", ":sort"]
y = "yank_joined"
Y = "yank_joined_to_clipboard"

# <backspace> for zellij commands
[keys.normal.backspace]
g = ":sh 'zellij run -fc --height 96% --width 96% -y 4% -x 2% -- lazygit'"
d = ":sh 'zellij run -fc --height 96% --width 96% -y 4% -x 2% -- gh dash'"
p = ''':sh 'zellij run -fc --height 84% --width 74% -y 8% -x 13% -- fish -c gh_pr_switch\ --wait-on-error''''
f = ":sh 'zellij run -fc --height 96% --width 96% -y 4% -x 2% -- yazi'"
F = ":sh 'zellij run -fc --height 96% --width 96% -y 4% -x 2% -- broot'"
